######################################################################
# Automatically generated by qmake (2.01a) ven 14. ott 15:04:08 2011
######################################################################

TEMPLATE = app
TARGET = ee
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR	+= ./
# Input
HEADERS += ModelExcel.h
SOURCES += main.cpp ModelExcel.cpp
