######################################################################
# Automatically generated by qmake (2.01a) mar ott 25 07:46:03 2011
######################################################################

TEMPLATE = app
TARGET = exhtml
DEPENDPATH += .   ../
INCLUDEPATH += .   ../

CONFIG   += -qt release
LANGUAGE	= C++

MOC_DIR	= build/.moc
RCC_DIR	= build/.rcc
OBJECTS_DIR = build/.obj


LIBS   += -L../ -lcole


# Input
SOURCES += main.c support.c xml.c html.c  ascii.c
