######################################################################
# Automatically generated by qmake (2.01a) ven ott 14 16:30:38 2011
######################################################################

TEMPLATE = app
TARGET = xmlformat
DEPENDPATH += .
INCLUDEPATH += .

MOC_DIR	= build/.moc
RCC_DIR	= build/.rcc
OBJECTS_DIR = build/.obj

QT += xml
QT += network
#### QT += sql


# Input
HEADERS += xmlhighlighter.h
SOURCES += main.cpp xmlhighlighter.cpp
