<?php
/**
* aheadWorks Co.
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://ecommerce.aheadworks.com/LICENSE-M1.txt
*
* @category   AW
* @package    AW_Advancedreports
* @copyright  Copyright (c) 2009-2012 aheadWorks Co. (http://www.aheadworks.com)
* @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
*/
/** @var AW_Advancedreports_Block_Chart $this */
?>
<?php if( $this->canShow() ): ?>
<?php $_containerStyle = "width:{$this->getWidth()}px;height:{$this->getHeight()}px; "; ?>
<?php if ($this->_type === AW_Advancedreports_Block_Chart::CHART_TYPE_MAP) : ?>
<script type="text/javascript">
awarcountry.drawChart(<?php echo Zend_Json::encode($this->getDataForMap()) ?>);
</script>
<div id='chart_div' style="<?php echo $_containerStyle ?>;margin: 0 auto;"></div>
<?php else : ?>
<p style="margin:0 auto; padding-bottom: 5px; text-align:center;"><img src="<?php echo $this->getTunnelUrl(true) ?>" alt="<?php echo $this->__('Chart'); ?>" title="<?php echo $this->__('Chart'); ?>" /></p>
<?php endif ?>
<?php else:  ?>
<p class="switcher" style="margin:0 auto; padding-bottom: 5px; text-align:center; color: #666;"><?php echo $this->__('It is not possible to build the chart.').'<br />'.$this->__('Please use shorter period or decrease the granularity (use month instead of day for long periods).') ?></p>
<?php endif; ?>
<?php echo "<!--".__FILE__.":".__LINE__."   57FGTZHUJKIOMJNHCDERF  end stamp Thu Apr 26 9:22:21 CEST 2012 file   -->"; ?>