<?php
/**
* aheadWorks Co.
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://ecommerce.aheadworks.com/LICENSE-M1.txt
*
* @category   AW
* @package    AW_Advancedreports
* @copyright  Copyright (c) 2009-2011 aheadWorks Co. (http://www.aheadworks.com)
* @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
*/
?>
<div class="aw-arep-setup">
<img class="v-middle" src="<?php echo $this->getSkinUrl('aw_advancedreports/images/customization.png'); ?>" /><a href="<?php echo $this->getSetupUrl(); ?>"><span><?php echo $this->__('Customization'); ?></span></a>
</div>